language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
sudo: required

notifications:
  email: true

branches:
  only:
    - master

install:
  - npm install -g npm@5.8.0
  - npm ci

script:
  - npm run lint
  - npm test
